name: aurora_mobile_engineer_assignment
description: "Aurora Mobile Engineer Assignment"

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.6.0
  flutter: 3.38.2

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  rxdart: ^0.28.0
  http: ^1.2.2
  logger: ^2.6.2
  simple_animations: ^5.1.0
  flutter_animate: ^4.5.2
  gaimon: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true

  # assets:
  # - assets/images/

  # fonts:
  # - assets/fonts/
